openapi: 3.0.0
tags:
  - name: Swagger Name
get:
  summary: Returns a user by ID.
  parameters:
    - name: x_input
      in: path
      required: true
      type: integer
      minimum: 1
      description: Parameter description in Markdown.
      schema:
        type: integer
responses:
    '200':
      description: Successful response
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error

